version: '3'
services:
  app:
    container_name: react
    stdin_open: true
    tty : true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: ./app
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./app:/app
    depends_on:
      - mongo
      - api
    links:
      - api
      - mongo


  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - '27015:27017'
    command: --quiet

  api:
    container_name: api
    restart: always
    build: ./api/.
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    links:
      - mongo

